/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_treescan_app_AppConstants */

#ifndef _Included_org_treescan_app_AppConstants
#define _Included_org_treescan_app_AppConstants
#ifdef __cplusplus
extern "C" {
#endif
#undef org_treescan_app_AppConstants_VERSION_MAJOR
#define org_treescan_app_AppConstants_VERSION_MAJOR 1L
#undef org_treescan_app_AppConstants_VERSION_MINOR
#define org_treescan_app_AppConstants_VERSION_MINOR 5L
#undef org_treescan_app_AppConstants_VERSION_RELEASE
#define org_treescan_app_AppConstants_VERSION_RELEASE 0L
/*
 * Class:     org_treescan_app_AppConstants
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_treescan_app_AppConstants_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     org_treescan_app_AppConstants
 * Method:    getWebSite
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_treescan_app_AppConstants_getWebSite
  (JNIEnv *, jclass);

/*
 * Class:     org_treescan_app_AppConstants
 * Method:    getSubstantiveSupportEmail
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_treescan_app_AppConstants_getSubstantiveSupportEmail
  (JNIEnv *, jclass);

/*
 * Class:     org_treescan_app_AppConstants
 * Method:    getTechnicalSupportEmail
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_treescan_app_AppConstants_getTechnicalSupportEmail
  (JNIEnv *, jclass);

/*
 * Class:     org_treescan_app_AppConstants
 * Method:    getReleaseDate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_treescan_app_AppConstants_getReleaseDate
  (JNIEnv *, jclass);

/*
 * Class:     org_treescan_app_AppConstants
 * Method:    getVersionId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_treescan_app_AppConstants_getVersionId
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
ndif
#e