/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_treescan_app_Parameters_AnalysisType */

#ifndef _Included_org_treescan_app_Parameters_AnalysisType
#define _Included_org_treescan_app_Parameters_AnalysisType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
