/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_treescan_app_CalculationThread */

#ifndef _Included_org_treescan_app_CalculationThread
#define _Included_org_treescan_app_CalculationThread
#ifdef __cplusplus
extern "C" {
#endif
#undef org_treescan_app_CalculationThread_MIN_PRIORITY
#define org_treescan_app_CalculationThread_MIN_PRIORITY 1L
#undef org_treescan_app_CalculationThread_NORM_PRIORITY
#define org_treescan_app_CalculationThread_NORM_PRIORITY 5L
#undef org_treescan_app_CalculationThread_MAX_PRIORITY
#define org_treescan_app_CalculationThread_MAX_PRIORITY 10L
/*
 * Class:     org_treescan_app_CalculationThread
 * Method:    RunAnalysis
 * Signature: (Lorg/treescan/app/Parameters;)I
 */
JNIEXPORT jint JNICALL Java_org_treescan_app_CalculationThread_RunAnalysis
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
