/*
 * ExceptionDialog.java
 *
 * Created on September 24, 2007, 8:24 AM
 */

package org.treescan.gui;

import java.awt.Desktop;
import java.awt.Dialog.ModalityType;
import java.awt.Window;
import javax.swing.JEditorPane;
import javax.swing.JOptionPane;
import org.treescan.app.AppConstants;
import org.treescan.gui.utils.JDocumentRenderer;
import org.treescan.utils.EmailClientLauncher;

/**
 *
 * @author  Hostovic
 */
public class ExceptionDialog extends javax.swing.JDialog {
    public static final long serialVersionUID = 1L;
    
    /** Creates new form ExceptionDialog */
    public ExceptionDialog(Window parent, Throwable e) {
        super(parent, "Exception!", ModalityType.DOCUMENT_MODAL);
        initComponents();
        _errorMessage.append("Message:\n");
        _errorMessage.append(e.getMessage());
        _errorMessage.append("\n\nException Type:\n");
        _errorMessage.append(e.getClass().getName());
        _errorMessage.append("\n\nStack Trace:");
        for (int i=0; i < e.getStackTrace().length; ++i)
            _errorMessage.append("\n" + e.getStackTrace()[i].getMethodName() + " of " + e.getStackTrace()[i].getClassName());
        _errorMessage.setCaretPosition(0);
        _emailButton.setEnabled(Desktop.isDesktopSupported());
        _printButton.setEnabled(Desktop.isDesktopSupported());
        setLocationRelativeTo(parent);
    }
    
    /**
     * Launches default email application and creates message detailing error.
     */
    private void launchDefaultClientEmail() {
        EmailClientLauncher launcher = new EmailClientLauncher();
        if (!launcher.launchDefaultClientEmail(getEmailAddress(), "Automated Error Message", _errorMessage.getText()))
            JOptionPane.showMessageDialog(this,  "Unable to launch default email application.", "Operation Failed", JOptionPane.INFORMATION_MESSAGE);
    }
    
    /** 
     * Attempts to get tech support email address; defaults to last known tech address.
     */
    private String getEmailAddress() {
        String emailAddress = "techsupport@treescan.org"; // default value
        try {
            emailAddress = AppConstants.getTechnicalSupportEmail();
        } catch (Throwable e) {
        }
        return emailAddress;
    }
    
    /**
     * Creates message detailing error, writes to file and prints.
     */
    private void print() {
        try {
            JDocumentRenderer documentRenderer = new JDocumentRenderer();
            documentRenderer.print(new JEditorPane("text/plain", "Automated Error Message:\n\n" + _errorMessage.getText()));            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,  "Unable to print.", "Operation Failed", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _AlarmInfo = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        _errorMessage = new javax.swing.JTextArea();
        _OkButton = new javax.swing.JButton();
        _printButton = new javax.swing.JButton();
        _emailButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        _AlarmInfo.setText("An unexpected exception occurred in the program.");

        _errorMessage.setColumns(20);
        _errorMessage.setEditable(false);
        _errorMessage.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        _errorMessage.setLineWrap(true);
        _errorMessage.setRows(5);
        jScrollPane.setViewportView(_errorMessage);

        _OkButton.setText("Ok");
        _OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _OkButtonActionPerformed(evt);
            }
        });

        _printButton.setText("Print");
        _printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _printButtonActionPerformed(evt);
            }
        });

        _emailButton.setText("Email");
        _emailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _emailButtonActionPerformed(evt);
            }
        });

        jLabel1.setText(" Please contact technical support with the following information:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addComponent(_AlarmInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(_printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(_emailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_AlarmInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_OkButton)
                    .addComponent(_emailButton)
                    .addComponent(_printButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void _printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__printButtonActionPerformed
        try {
            print();
        } catch (Throwable e) {}
    }//GEN-LAST:event__printButtonActionPerformed
    
    private void _emailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__emailButtonActionPerformed
        try {
            launchDefaultClientEmail();
        } catch (Throwable e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event__emailButtonActionPerformed
    
    private void _OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__OkButtonActionPerformed
        dispose();
    }//GEN-LAST:event__OkButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _AlarmInfo;
    private javax.swing.JButton _OkButton;
    private javax.swing.JButton _emailButton;
    private javax.swing.JTextArea _errorMessage;
    private javax.swing.JButton _printButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
    
}
