/*
 * StartDialog.java
 *
 * Created on December 11, 2007, 12:51 PM
 */

package org.treescan.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.treescan.app.ParameterHistory;
import org.treescan.gui.utils.JHyperLink;

/**
 *
 * @author  Hostovic
 */
public class StartDialog extends javax.swing.JDialog {
    enum StartType {NEW, SAVED, LAST, CANCEL};
    private StartType _openType = StartType.CANCEL;
    
    /**
     * Creates new form StartDialog
     */
    public StartDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        int i = ParameterHistory.getInstance().getHistoryList().size();
        lastLabel.setEnabled(ParameterHistory.getInstance().getHistoryList().size() > 0);
        setLocationRelativeTo(parent);
    }
    
    /**
     *
     */
    public StartType GetOpenType() {
        return _openType;
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newLabel = new JHyperLink();
        ((JHyperLink)newLabel).addActionListener( new ActionListener() {
            public void actionPerformed( ActionEvent e ) {
                _openType = StartType.NEW;
                setVisible(false);
            }
        } );
        savedLabel = new JHyperLink();
        ((JHyperLink)savedLabel).addActionListener( new ActionListener() {
            public void actionPerformed( ActionEvent e ) {
                _openType = StartType.SAVED;
                setVisible(false);
            }
        } );
        lastLabel = new JHyperLink();
        ((JHyperLink)lastLabel).addActionListener( new ActionListener() {
            public void actionPerformed( ActionEvent e ) {
                _openType = StartType.LAST;
                setVisible(false);
            }
        } );
        cancelLabel = new JHyperLink();
        ((JHyperLink)cancelLabel).addActionListener( new ActionListener() {
            public void actionPerformed( ActionEvent e ) {
                _openType = StartType.CANCEL;
                setVisible(false);
            }
        } );

        setTitle("Start Window");
        setModal(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Welcome to TreeScan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        newLabel.setText("Create New Session");

        savedLabel.setText("Open Saved Session");

        lastLabel.setText("Open Last Session");

        cancelLabel.setText("Cancel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newLabel)
                    .addComponent(savedLabel)
                    .addComponent(lastLabel)
                    .addComponent(cancelLabel))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newLabel)
                .addGap(15, 15, 15)
                .addComponent(savedLabel)
                .addGap(15, 15, 15)
                .addComponent(lastLabel)
                .addGap(15, 15, 15)
                .addComponent(cancelLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastLabel;
    private javax.swing.JLabel newLabel;
    private javax.swing.JLabel savedLabel;
    // End of variables declaration//GEN-END:variables
    
}
